### PR TITLE
Add readme

### PR DESCRIPTION
**Pull request by venmario**
Adding a README file that was missing on the project

### CODE REVIEW

**Comment by HaiderAlalawi** [comment]
add readme file

**Comment by Paddorn** [comment]
add readme file

**Comment by jameskelly247** [comment]
add read me

**Comment by apsinghdev** [comment]
add a readme file

**Comment by jose-inzunza** [comment]
Add a README.md file

**Comment by visccyberacct** [comment]
Added a README.md file

**Comment by VladoPenchev** [comment]
Add a README.md file.

**Comment by DEVASSRI** [comment]
Adding a README.md file to the repo

**Comment by amin-omidzade** [comment]
Adding a README file that was missing on the project

**Comment by Chiri72** [comment]
Adding a README file that was missing on the project.

**Comment by SamuelPHIL** [comment]
Adding a missing README file to the project

**Comment by alexisearl14** [comment]
Adding a missing README.md file to the project

**Comment by pablotebb** [comment]
pruebon

**Comment by RicardoUrias** [comment]
Pleas add

**Pull request closed without merging**
